### ISSUE TITLE
conda build --output does not consider __conda_version__.txt

### ISSUE THREAD

**Issue by flamingbear** [anaconda-graveyard/anaconda-build#82]
I'm trying to put together a build workflow.  If you overwrite the default
version with a `__conda_version__.txt` file during your build, you don't have
access to the built artifact to push to anaconda.org with `conda build . --output`

I started in the anaconda-client/example-packages/conda directory and added a file
`__conda_version__.txt` with contents:

```
2.0.0dev
```

`$ conda build .`

```
Removing old build environment
Removing old work directory
BUILD START: conda_gc_test-2.0.0-py27_1
Removing old work directory
Copying /Users/savoie/projects/anaconda-client/example-packages/conda to /Users/savoie/anaconda/conda-bld/work
Package: conda_gc_test-2.0.0-py27_1
source tree in: /Users/savoie/anaconda/conda-bld/work
+ echo Building
Building
Setting version from __conda_version__.txt: 2.0.0dev
number of files: 0
Fixing permissions
Fixing permissions
BUILD END: conda_gc_test-2.0.0dev-py27_1
Nothing to test for: conda_gc_test-2.0.0dev-py27_1
# If you want to upload this package to anaconda.org later, type:
#
# $ anaconda upload /Users/savoie/anaconda/conda-bld/osx-64/conda_gc_test-2.0.0dev-py27_1.tar.bz2
#
# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

```

`$ conda build . --output`

```
/Users/savoie/anaconda/conda-bld/osx-64/conda_gc_test-2.0.0-py27_1.tar.bz2
```

Maybe I'm missing something, but it would be nice to be able to know what the artifact built is for pushing to anaconda.org

**Comment by flamingbear** [comment]
The problem is that I want to overwrite a dev version on anaconda.org.

to upload I'd run:
`anaconda upload --force /Users/savoie/anaconda/conda-bld/osx-64/conda_gc_test-2.3.4-py27_1.tar.bz2`

but in reality since I don't know the artifact this would be ideal:
`conda build .`
``anaconda upload --force `build . --output` ``

I can set the build to upload in my `.condarc` with
`$ conda config --set anaconda_upload yes`

But then my second build won't upload.

```
$ conda build .
Removing old build environment
Removing old work directory
BUILD START: conda_gc_test-2.0.0-py27_1
Removing old work directory
Copying /Users/savoie/projects/anaconda-client/example-packages/conda to /Users/savoie/anaconda/conda-bld/work
Package: conda_gc_test-2.0.0-py27_1
source tree in: /Users/savoie/anaconda/conda-bld/work
+ echo Building
Building
Setting version from __conda_version__.txt: 2.3.4
number of files: 0
Fixing permissions
Fixing permissions
BUILD END: conda_gc_test-2.3.4-py27_1
Nothing to test for: conda_gc_test-2.3.4-py27_1
Uploading to anaconda.org
Using binstar api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file matthewsavoie/conda_gc_test/2.3.4/osx-64/conda_gc_test-2.3.4-py27_1.tar.bz2 ... 
Distribution already exists. Please use the -i/--interactive or --force options or `anaconda remove matthewsavoie/conda_gc_test/2.3.4/osx-64/conda_gc_test-2.3.4-py27_1.tar.bz2`
[Conflict] file osx-64/conda_gc_test-2.3.4-py27_1.tar.bz2 already exists for package conda_gc_test version 2.3.4 
```


So I'm not sure where this bug/feature lives.  In anaconda-upload or conda-build, but I'd really like to be able to overwrite the conda version with `__conda_version__.txt` and upload force that file.

Let me know if I can describe what I'm looking for better.

Thanks
Matt

**Comment by srossross** [comment]
Thanks @flamingbear we are taking a look at this now.

**Comment by srossross** [comment]
@csoja should this be logged in the conda repo?

cc @stephenakearns
